#!/usr/bin/perl
use v5.14.2;
use strict;
use warnings;

my $time = localtime;
my $USER = $ENV{USER};

my $log_file = "/var/log/git-hooks/pre-receive-reject-binaries.log";
open my $fh, ">>", $log_file or die "PANIC: Unable to open($log_file): <$!>";
while (my $line = <STDIN>) {
    print $fh "$time - $USER - $line";
}
close $fh or die "PANIC: Unable to close($log_file): <$!>";
